### ISSUE TITLE
continue if there is no valid pred box

### ISSUE THREAD

**Issue by danish87** [fnozarian/OpenPCDet#13]
An exception has been raised in a case where we don't have any valid prediction in that case valid_pred_boxes is empty and cat operation can not be performed as pred_scores[i] was filled with zero in the previous stage (that filling should be with -1 and we can filter pred_scores[i] here)

https://github.com/fnozarian/OpenPCDet/blob/c5782fe114497ac9abe7dab156538bc59b22ca93/pcdet/utils/stats_utils.py#L63-L72
I am not sure but we have to check if we could 
1. Skip the ith iteration if valid_preds_mask.sum()==0 or (not len(valid_pred_boxes))
2. Make an assert valid_pred_mask.sum()==len(pred_scores[i])

Filling part:
https://github.com/fnozarian/OpenPCDet/blob/c5782fe114497ac9abe7dab156538bc59b22ca93/pcdet/models/detectors/pv_rcnn_ssl.py#L565

**Comment by fnozarian** [comment]
Thanks. I fixed this by filtering invalid rows, same as `valid_pred_boxes` and `valid_gt_boxes`.

**Comment by danish87** [comment]
It will be nice if we have the same protocol for all invalid entries

![image](https://user-images.githubusercontent.com/32911344/190582533-0ffdb12d-59c6-44f4-981a-60c968f8da63.png)

Then we can compare and create mask using torch.isnan(pseudo_label[0]):

**Comment by fnozarian** [comment]
It is currently the same protocol for all invalid entries: we fill with zeros. I just forgot to filter them (even though I'd put a todo for that)
