### ISSUE TITLE
Recall values getting overriden in calc_statistics_new()

### ISSUE THREAD

**Issue by shashankag14** [fnozarian/OpenPCDet#14]
While iterating over different classes, `max/mean recall` values in `statistics` are getting overriden with new values. 
https://github.com/fnozarian/OpenPCDet/blob/fe56e561e9a1fa7f558b4aceeadb37b0a11effee/pcdet/models/detectors/pv_rcnn_ssl.py#L370-L373

May be we can do something like we are doing for storing the `precision` i.e. adding the values for each class in `class_metrics_all` and storing this dictionary in `statistics`:
https://github.com/fnozarian/OpenPCDet/blob/fe56e561e9a1fa7f558b4aceeadb37b0a11effee/pcdet/models/detectors/pv_rcnn_ssl.py#L362-L368

**Comment by fnozarian** [comment]
Yes, I also noticed that. [Fixed](https://github.com/fnozarian/OpenPCDet/commit/726e7a674ec4d0d57d1e2d1a4825e07b30376def). Thanks
