### ISSUE TITLE
ignored_threshold in stats_utils is incorrect due to (probably) dtype issue?

### ISSUE THREAD

**Issue by fnozarian** [fnozarian/OpenPCDet#16]
![Screenshot from 2022-09-16 12-20-22](https://user-images.githubusercontent.com/4715200/190618253-8d6bfbbc-47cb-46fa-9ad4-245b14102eb9.png)
![Screenshot from 2022-09-16 12-20-38](https://user-images.githubusercontent.com/4715200/190618552-8274fbc8-66f1-42af-b37f-10cce2b47fb0.png)

UPDATE: another weird example!
![Screenshot from 2022-09-16 12-31-02](https://user-images.githubusercontent.com/4715200/190619686-f0a35564-b8e7-43b3-9b83-b8d22f072232.png)

**Comment by danish87** [comment]
I guess it would be solved if we use double, which work for cpu() and cuda() as well

if (dt_scores[i].double() < thresh.double())
