### ISSUE TITLE
Mean computation for per batch states

### ISSUE THREAD

**Issue by shashankag14** [fnozarian/OpenPCDet#18]
The following per-batch states are being updated with mean values in `update()` :
https://github.com/fnozarian/OpenPCDet/blob/9890d68c79fb6dac24d57650a1e7e6f40863358f/pcdet/utils/stats_utils.py#L133-L139

When `compute()` is called, these states are already scalar tensors, so the mean computation can be avoided here.
https://github.com/fnozarian/OpenPCDet/blob/9890d68c79fb6dac24d57650a1e7e6f40863358f/pcdet/utils/stats_utils.py#L141-L145

**Comment by fnozarian** [comment]
When the `compute()` is called, all scalars from different dist. processes are gathered and con`cat`ed into one tensor (see the the`dist_reduce_fx` of states). Thus the final tensor should be reduced with `mean` again.

**Comment by shashankag14** [comment]
I see. I missed out on the part that distributed setting requires this. Thanks for the clarification !
