### ISSUE TITLE
[DA-7] Repetitive BG samples due to mismatch in ROIs per image

### ISSUE THREAD

**Issue by shashankag14** [fnozarian/OpenPCDet#23]
Currently we have 100 `max_overlap` i.e. 100 proposals coming from the Teacher
https://github.com/fnozarian/OpenPCDet/blob/ea99bee1214c7b5c50477462bbb6d1bb5abe8153/pcdet/models/roi_heads/target_assigner/proposal_target_layer_consistency.py#L141-L143

Whereas, while doing subsampling based on FG-BG ratio, we have `self.roi_sampler_cfg.ROI_PER_IMAGE=128`, due to which we are sampling some repetitive BGs.
https://github.com/fnozarian/OpenPCDet/blob/ea99bee1214c7b5c50477462bbb6d1bb5abe8153/pcdet/models/roi_heads/target_assigner/proposal_target_layer_consistency.py#L220

Example of sampled indices for BGs:
![image](https://user-images.githubusercontent.com/74488693/197827698-4e49442d-72e4-473c-8a8f-9431f299399c.png)

Can we avoid this repetition by keeping `self.roi_sampler_cfg.ROI_PER_IMAGE=100` and setting the remaining ROIs and their corresponding `reg_valid_mask` and `rcnn_cls_labels` as invalid (like we were doing before in `_override_unlabeled_target`) ?

**Comment by fnozarian** [comment]
Yes, hyper-parameters for this version are not yet tuned/adjusted. What if we switch back to the original `NMS_CONFIG.TEST.NMS_POST_MAXSIZE=128`?

**Comment by shashankag14** [comment]
Okay. Yes, we can switch to 128 teacher proposals.
