### ISSUE TITLE
Bug: missing mask for roi case in metrics update

### ISSUE THREAD

**Issue by fnozarian** [fnozarian/OpenPCDet#25]
@shashankag14 The following line has been changed in the main consistency branch. Please fix it in `DA-20-roi-aug` branch and make sure this has not influenced your analysis.

https://github.com/fnozarian/OpenPCDet/blob/9298ba61f6dbdb601034f621e15fcde06ae4cd76/pcdet/models/roi_heads/roi_head_template.py#L198

https://github.com/fnozarian/OpenPCDet/blob/3192d4d70ef3e576b979403ba5907d1ff4f7f316/pcdet/models/roi_heads/roi_head_template.py#L198

**Comment by shashankag14** [comment]
Thanks @fnozarian for sharing this information. 
I have merged the latest [`soft-teacher-reliable_metrics`](https://github.com/fnozarian/OpenPCDet/commit/3192d4d70ef3e576b979403ba5907d1ff4f7f316) into [`DA-20-roi-aug`](https://github.com/fnozarian/OpenPCDet/commit/aee6097b79ab4d5b5ecfe11203bfce9d9a60dce1). This merge fixes the above issue in the ROI augmentation pipeline and also enables analyzing the latest metrics on top of ROI augs.
