### ISSUE TITLE
DA-18 Running code on headless (no display integrated) server 

### ISSUE THREAD

**Issue by shashankag14** [fnozarian/OpenPCDet#26]
Current code imports `mayavi` in `pv_rcnn_ssl.py` and `roi_head_template.py` to visualize the boxes at different stages.
https://github.com/fnozarian/OpenPCDet/blob/9173644af32cab4fc31df024a14e79f3c7bcc1b0/pcdet/models/detectors/pv_rcnn_ssl.py#L17-L18

Running the same code on the cluster would fail, since we do not have the display support on that server. Following is a workaround in order to import `mayavi` based on the presence of display during runtime and avoid code failure.

```
if os.name == 'posix' and "DISPLAY" not in os.environ:
    headless_server = True
else:
    headless_server = False
    import mayavi.mlab as mlab
    from visual_utils import visualize_utils as V
```

**Comment by fnozarian** [comment]
@shashankag14 thanks! Could you please fix and merge it?
